DATA = {
               "Structural Analysis": "Figuring out how buildings and bridges hold up under weight.  Uses: Designing safe structures.",
               "Statics": "Understanding forces that are balanced. Uses: Making sure things don't fall down.",
               "Dynamics": "Understanding forces when things are moving. Uses: Designing structures that can handle earthquakes or wind.",
               "Soil Mechanics": "How soil behaves. Uses: Building strong foundations.",
               "Foundation Engineering": "Designing the base of structures. Uses: Making sure buildings are stable.",
               "Geotechnical Engineering": "How structures interact with the ground. Uses: Safe building construction.",
               "Concrete Technology": "Understanding and using concrete. Uses: Building with concrete.",
               "Steel Design": "Designing structures using steel. Uses: Building strong steel structures.",
               "Construction Management": "Planning and running construction projects. Uses: Getting projects done on time and budget.",
               "Transportation Engineering": "Designing roads and highways. Uses: Building transportation systems.",
               "Water Resources Engineering": "Managing water supplies. Uses: Designing dams and irrigation.",
               "Environmental Engineering": "Protecting the environment during construction. Uses: Keeping construction environmentally friendly.",
               "Surveying": "Measuring land and making maps. Uses: Planning construction projects.",
               "Hydraulic Engineering": "Understanding water flow. Uses: Designing water systems.",
               "Construction Materials": "Studying different building materials. Uses: Choosing the right materials for a job.",
               "Structural Design": "Designing safe and strong structures. Uses: Creating safe buildings and bridges.",
               "Finite Element Analysis (FEA)": "Using computers to test designs. Uses: Making sure designs are strong enough.",
               "Building Information Modeling (BIM)": "Using computer models to plan buildings. Uses: Better construction planning.",
               "Geographic Information Systems (GIS)": "Using maps and data for planning. Uses: Planning infrastructure projects.",
               "Construction Safety": "Keeping construction workers safe. Uses: Preventing accidents on construction sites.",
               "Sustainability in Civil Engineering": "Building environmentally friendly structures. Uses: Reducing the impact of construction on the environment.",
               "Geomechanics": "Understanding how rocks and soil behave. Uses: Designing underground structures.",
               "Earthquake Engineering": "Designing structures to withstand earthquakes. Uses: Building earthquake-resistant structures.",
               "Wind Engineering": "Understanding how wind affects structures. Uses: Designing wi-resistant structures.",
               "Bridge Engineering": "Designing and building bridges. Uses: Connecting areas with bridges.",
               "Tunneling": "Designing and building tunnels. Uses: Building underground transportation.",
               "Coastal Engineering": "Protecting coastlines. Uses: Preventing coastal erosion.",
               "Traffic Engineering": "Improving traffic flow. Uses: Reducing traffic congestion.",
               "Urban Planning": "Planning cities and towns. Uses: Designing sustainable cities.",
               "Construction Planning": "Planning how to build something. Uses: Efficient construction projects.",
                }
a = input("say 'Earthquake Engineering' ")
print(DATA[a])      